name: flutter_resource_generator_example
description: example
version: 1.0.0
homepage: https://github.com/ymyplss/flutter_resource_generator

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.8.1
  flutter_resource_generator: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    #Image
    - assets/image/close_a.png
    - assets/image/close_b.png
