name: flutter_resource_generator
description: Generator resource class automatically by only one commnad based on build runner and dart script, avoid inputing resource file path manually
version: 1.1.2
homepage: https://github.com/ymyplss/flutter_resource_generator

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  source_gen: ^0.9.7+1
  build_runner: ^1.8.1
  build: ^1.5.0
  analyzer: ">=0.40.4 <2.0.0"
  path: ^1.7.0
  args: ^1.6.0
  collection: ^1.14.13


executables:
  rgen: flutter_resource_generator


